<?php

namespace Bloggr\BlogBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Bloggr\BlogBundle\Entity\User;
use Bloggr\BlogBundle\Form\UserType;


class UsersController extends Controller
{

    /**
     * @Route("/Users", name="users")
     */
    public function usersAction(Request $request)
    {
        $user = $this->getUser();
        $entityManager = $this->getDoctrine()->getManager();
//        print_r($user->getUsername());  // получение  объекта
//        exit;
//        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $user->getPhoto();

            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            $file->move(
                $this->getParameter('photo_directory'),
                $fileName
            );

            $user->setPhoto(null);
            $user->setPhotoName($fileName);
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirect($this->generateUrl('users'));
        }

        $foto = $user->getPhotoName();

        return $this->render('BlogBundle:Users:user.html.twig', array(
            'form' => $form->createView(),
            'foto' => $foto,
        ));
    }

    /**
    * @return string
    */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
